dist: trusty
sudo: required
language: java
jdk: openjdk11

before_install:
  # - docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
  - sudo apt -y  install software-properties-common
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt -y install podman

install:
  # - pip install ansible
  # - ansible-galaxy install -r apb/requirements-travis.yml
  # - ansible-playbook apb/playbooks/provision.yml --syntax-check

script:
  - make build

after_success:
  # - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # - docker tag tqvarnst/quarkus-workshop-apb:$TRAVIS_COMMIT quay.io/tqvarnst/quarkus-workshop-apb:$TAG
  # - docker push quay.io/tqvarnst/quarkus-workshop-apb:$TAG
  # - docker tag tqvarnst/che-quarkus:$TRAVIS_COMMIT quay.io/tqvarnst/che-quarkus:$TAG
  # - docker push quay.io/tqvarnst/che-quarkus:$TAG